### PR TITLE
Declarative Limits

### PR DESCRIPTION
**Pull request by jezzsantos**
I've updated all ServiceStack nugets to 4.5.14, and all testing tools to latest versions, in preparation for a future pull request as discussed: #2 

There is one outstanding unit test that I cannot fathom, and hoping you would resolve.
I'm not having a great time with XUnit (not familiar with it) and tests that need an AppHost running. Can you help?

### CODE REVIEW

**Comment by jezzsantos** [comment]
At this point, I think I have a `ILimitProvider` for you.
I'd like to write some integration tests to prove it works as advertised, can you help me do that in your codebase? (like where and what language). Perhaps you go first?

**Comment by wwwlicious** [comment]
Thanks @jezzsantos 
I'll try and make some time during next week to look at it. I've found the easiest way to do integration testing is to create a project with a selfhosted app as an xunit collection fixture. You can then create a client and get end-to-end testing. I'll put something together for the config based rate limiter for you to work from.

**Comment by jezzsantos** [comment]
Thanks. That will be a great way to set the pattern for this project.

**Comment by wwwlicious** [comment]
oh and thanks for the PR work, much appreciated. 👍

**Comment by jezzsantos** [comment]
Cheers, looking forward to using it

**Comment by jezzsantos** [comment]
Why does the nuspec include a specific (explicit) dependency on `ServiceStack.Server`?

Can't that be removed?

The consumer really does not need either of these assemblies installed in their service for this plugin, do they?
* `ServiceStack.OrmLite`
* `ServiceStack.Server`

**Comment by wwwlicious** [comment]
ServiceStack.Server is the package plugins should use in general afaik. 

I still have to update the projects to vs2017 format at which point it would be the only package referenced.

**Comment by wwwlicious** [comment]
I'll merge this in for now then convert the projects while I sort out the tests

**Comment by jezzsantos** [comment]
Yeah, Im not so sure that you need the explicit reference to `ServiceStack.Server` though, just to consume the plugin.

**Comment by jezzsantos** [comment]
thanks for all that 👍

**Comment by wwwlicious** [comment]
the goal of the server package is to be the minimum required to run a servicestack service.
You can't with less, the plugin might not require it all, but you can't use the plugin in a project that doesn't have all it's dependencies.
 
Perhaps in the new packaging world it doesn't make as much sense but it is still valid i.e. whether you install that package or not, you'll have all it's dependencies...

**Comment by wwwlicious** [comment]
the goal of the server package is to be the minimum required to run a servicestack service.
You can't with less, the plugin might not require it all, but you can't use the plugin in a project that doesn't have all it's dependencies.
 
Perhaps in the new packaging world it doesn't make as much sense but it is still valid i.e. whether you install that package or not, you'll have all it's dependencies...

**Pull request merged**
